In [2]:
import pandas as pd 
import numpy as np

# reading , clean data , rename columns

In [3]:
sales = pd.read_excel('WoodInc-sale.xlsx')    
sales.head()

,تاريخ,شماره,کد مشتري,نام مشتري,کد کالا,نام کالا,واحد,مقدار,في,مبلغ,ماليات,تخفيف,عوارض,مبلغ خالص,تاريخ تسويه,سريال انبار
0,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-706,ملامينه 210*280 كد 361 سفيد صابوني كيميا ...,ورق ...,5.0,2339450,11697250,1052753,0,0,12750003,,82308
1,13990105,82516,1101328,ابوالفضل تام ...,1-1-01-505,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,ورق ...,2.0,596330,1192660,107339,0,0,1299999,,82308
2,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-023,ملامينه 204*260 كد 79 آنتيك سويز درجه A ...,ورق ...,5.0,2293578,11467890,1032110,0,0,12500000,,82308
3,13990105,82517,1100140,احساني عليرضا ...,1-1-05-137,نئوپان 210*366 خام ممتاز گلستان درجه B ...,ورق ...,3.0,1788991,5366973,483028,0,0,5850001,,82309
4,13990105,82518,1101464,مطهري مهدي ...,1-1-01-294,ام دي اف 183*366 سفيد صابوني كيميا چوب ...,ورق ...,2.0,3669725,7339450,660551,0,0,8000001,,82310

In [4]:
sales.columns = [ 'date' , 'ID' , 'Customer_ID','Customer_Name' , 'Item_Code' , 'Description' , 'Unit' , 'Quantity','Unit Price' , 'Amount' , 'Tax' ,'Discount',
                    'Duties' , 'Net Amount' , 'Payment Date' , 'Warehouse Serial' ] 

sales.head()

,date,ID,Customer_ID,Customer_Name,Item_Code,Description,Unit,Quantity,Unit Price,Amount,Tax,Discount,Duties,Net Amount,Payment Date,Warehouse Serial
0,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-706,ملامينه 210*280 كد 361 سفيد صابوني كيميا ...,ورق ...,5.0,2339450,11697250,1052753,0,0,12750003,,82308
1,13990105,82516,1101328,ابوالفضل تام ...,1-1-01-505,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,ورق ...,2.0,596330,1192660,107339,0,0,1299999,,82308
2,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-023,ملامينه 204*260 كد 79 آنتيك سويز درجه A ...,ورق ...,5.0,2293578,11467890,1032110,0,0,12500000,,82308
3,13990105,82517,1100140,احساني عليرضا ...,1-1-05-137,نئوپان 210*366 خام ممتاز گلستان درجه B ...,ورق ...,3.0,1788991,5366973,483028,0,0,5850001,,82309
4,13990105,82518,1101464,مطهري مهدي ...,1-1-01-294,ام دي اف 183*366 سفيد صابوني كيميا چوب ...,ورق ...,2.0,3669725,7339450,660551,0,0,8000001,,82310

In [5]:
sales.replace(["NaN", "None", "null", "", " "], np.nan, inplace=True)

In [6]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28274 entries, 0 to 28273
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              28274 non-null  int64
 1   ID                28274 non-null  int64
 2   Customer_ID       28274 non-null  int64
 3   Customer_Name     28274 non-null  object
 4   Item_Code         28274 non-null  object
 5   Description       28274 non-null  object
 6   Unit              28274 non-null  object
 7   Quantity          28274 non-null  float64
 8   Unit Price        28274 non-null  int64
 9   Amount            28274 non-null  int64
 10  Tax               28274 non-null  int64
 11  Discount          28274 non-null  int64
 12  Duties            28274 non-null  int64
 13  Net Amount        28274 non-null  int64
 14  Payment Date      28274 non-null  object
 15  Warehouse Serial  28274 non-null  int64
dtypes: float64(1), int64(10), object(5)
memory usage: 3.5+ MB

In [7]:
sales.nunique()

date                  289
ID                  16353
Customer_ID           687
Customer_Name         681
Item_Code             737
Description           737
Unit                    6
Quantity              196
Unit Price            336
Amount               2893
Tax                  2475
Discount              222
Duties                  1
Net Amount           3159
Payment Date          225
Warehouse Serial    16353
dtype: int64

In [8]:
sales.isnull().sum(axis = 0)

date                0
ID                  0
Customer_ID         0
Customer_Name       0
Item_Code           0
Description         0
Unit                0
Quantity            0
Unit Price          0
Amount              0
Tax                 0
Discount            0
Duties              0
Net Amount          0
Payment Date        0
Warehouse Serial    0
dtype: int64

In [9]:
sales.isnull().sum().sum()

0

In [10]:
sales.duplicated(keep=False).sum()

41

In [11]:
dups1       = sales.duplicated(keep = False) 
dups_sales = sales.loc[dups]
dups_sales.head()

NameError: name 'dups' is not defined

In [ ]:
sales.drop_duplicates(inplace=True)

In [ ]:
sales.Customer_Name.str.strip()

0           ابوالفضل تام
1           ابوالفضل تام
2           ابوالفضل تام
3          احساني عليرضا
4             مطهري مهدي
              ...
28269          سبزي مهدي
28270    محمد جواد حيدري
28271      احساني عليرضا
28272      سيد علي موسوي
28273        احسان مولوي
Name: Customer_Name, Length: 28252, dtype: object

In [ ]:
sales.Description.str.strip()

0          ملامينه 210*280 كد 361 سفيد صابوني كيميا
1         اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A
2           ملامينه 204*260 كد 79 آنتيك سويز درجه A
3            نئوپان 210*366 خام ممتاز گلستان درجه B
4            ام دي اف 183*366 سفيد صابوني كيميا چوب
                            ...
28269                     نئوپان 210*305 خام درجه 1
28270            ام دي اف 210*366 كد 60 ونگه درجه A
28271      ملامينه 210*366 كد 70 گردويي تيره درجه A
28272                         نئوپان 204*260 خام 2%
28273    ام دي اف 183*366 كد 946 نولا اكسترا درجه 1
Name: Description, Length: 28252, dtype: object

# جمع کل خرید هر مشتری

In [ ]:
Customer_buy = sales.groupby('Customer_Name')['Net Amount'].sum().reset_index()
Customer_buy.tail()

                                         Customer_Name  Net Amount
676  کاظمي جواد                                    ...   444599982
677  گروه صنعتي لينا                               ...    33999999
678  گزشيرين شاد                                   ...    36360002
679  گلزار محسن                                    ...  2763470063
680  گنجي حسين                                     ...    25110000

In [ ]:
sales.groupby('Customer_Name').ngroups

681

## ترتیب سه مشتری برا اساس میزان خرید

In [ ]:
top_customer = Customer_buy.sort_values(ascending= False , by = 'Net Amount')
top_customer.reset_index()

     index                                      Customer_Name   Net Amount
0      438  فخار زاده هادي                                ...  32880404682
1      570  مصطفي نوحي                                    ...  30843447535
2      545  مختاري احمد                                   ...  27524560602
3      270  زيارتي اراك                                   ...  24832320429
4      434  غلامي محمد                                    ...  20601772249
..     ...                                                ...          ...
676    416  عليزاده سلمان                                 ...       399999
677    536  محمدي سپهر                                    ...       300001
678    584  منصوري جامع كيا                               ...       200000
679    633  نجار قمي ابوالفضل                             ...           33
680    290  سيد احمد سادات حسيني                          ...            4

[681 rows x 3 columns]

###  کل خرید مشتری

In [ ]:
total_buy = Customer_bye['Net Amount'].sum()
total_buy

737002540040

#### سهم هر یک از کل فروش شرکت

In [ ]:
customer_buy_share = (sales.groupby('Customer_Name' )['Net Amount'].sum()/ total_buy) * 100

In [ ]:
customer_buy_share_df = customer_buy_share.reset_index()

customer_buy_share_df.columns = ['Customer_Name','Share_Total_buy']
customer_buy_share_df.head(3)

                                       Customer_Name  Share_Total_buy
0  آزادي اعتماد                                  ...         0.619660
1  آسيابان سعيد                                  ...         0.185664
2  آقا زيارتي علي                                ...         1.037736

In [ ]:
customer_buy_share_df.sort_values(ascending= False , by = 'Share_Total_buy')

                                         Customer_Name  Share_Total_buy
438  فخار زاده هادي                                ...     4.461369e+00
570  مصطفي نوحي                                    ...     4.184985e+00
545  مختاري احمد                                   ...     3.734663e+00
270  زيارتي اراك                                   ...     3.369367e+00
434  غلامي محمد                                    ...     2.795346e+00
..                                                 ...              ...
416  عليزاده سلمان                                 ...     5.427376e-05
536  محمدي سپهر                                    ...     4.070556e-05
584  منصوري جامع كيا                               ...     2.713695e-05
633  نجار قمي ابوالفضل                             ...     4.477597e-09
290  سيد احمد سادات حسيني                          ...     5.427390e-10

[681 rows x 2 columns]

In [ ]:
top_customer.to_excel('top_customer.xlsx')
customer_buy_share_df.to_excel('buy_share.xlsx')

In [ ]:
top_customer1 = pd.read_excel('top_customer.xlsx')
sale_buy1 = pd.read_excel('buy_share.xlsx')

In [ ]:
top_customer1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681 entries, 0 to 680
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     681 non-null    int64
 1   Customer_Name  681 non-null    object
 2   Net Amount     681 non-null    int64
dtypes: int64(2), object(1)
memory usage: 16.1+ KB

In [ ]:
top_customer1 = top_customer1.drop('Unnamed: 0' , axis=1)

In [ ]:
merge_data_buy = pd.merge( left = top_customer1 ,
                        right= sale_buy1 ,
                        on = 'Customer_Name' , 
                        how = 'inner' , 
                        
                        )
merge_data_buy

,Customer_Name,Net Amount,Unnamed: 0,Share_Total_buy
0,فخار زاده هادي ...,32880404682,438,4.461369e+00
1,مصطفي نوحي ...,30843447535,570,4.184985e+00
2,مختاري احمد ...,27524560602,545,3.734663e+00
3,زيارتي اراك ...,24832320429,270,3.369367e+00
4,غلامي محمد ...,20601772249,434,2.795346e+00
...,...,...,...,...
676,عليزاده سلمان ...,399999,416,5.427376e-05
677,محمدي سپهر ...,300001,536,4.070556e-05
678,منصوري جامع كيا ...,200000,584,2.713695e-05
679,نجار قمي ابوالفضل ...,33,633,4.477597e-09
680,سيد احمد سادات حسيني ...,4,290,5.427390e-10

In [ ]:
merge_data_buy = merge_data_buy.drop('Unnamed: 0' , axis=1)

In [ ]:
merge_data_buy['Share_Total_buy'].sum()

100.0

# سه مشتری با بیشترین میزان خرید و سهم هر یک از کل فروش شرکت

In [ ]:
merge_data_buy

,Customer_Name,Net Amount,Share_Total_buy
0,فخار زاده هادي ...,32880404682,4.461369e+00
1,مصطفي نوحي ...,30843447535,4.184985e+00
2,مختاري احمد ...,27524560602,3.734663e+00
3,زيارتي اراك ...,24832320429,3.369367e+00
4,غلامي محمد ...,20601772249,2.795346e+00
...,...,...,...
676,عليزاده سلمان ...,399999,5.427376e-05
677,محمدي سپهر ...,300001,4.070556e-05
678,منصوري جامع كيا ...,200000,2.713695e-05
679,نجار قمي ابوالفضل ...,33,4.477597e-09
680,سيد احمد سادات حسيني ...,4,5.427390e-10

# برترین مشتری ها  در هر ماه از سال

In [ ]:
sales.head()

,date,ID,Customer_ID,Customer_Name,Item_Code,Description,Unit,Quantity,Unit Price,Amount,Tax,Discount,Duties,Net Amount,Payment Date,Warehouse Serial
0,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-706,ملامينه 210*280 كد 361 سفيد صابوني كيميا ...,ورق ...,5.0,2339450,11697250,1052753,0,0,12750003,,82308
1,13990105,82516,1101328,ابوالفضل تام ...,1-1-01-505,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,ورق ...,2.0,596330,1192660,107339,0,0,1299999,,82308
2,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-023,ملامينه 204*260 كد 79 آنتيك سويز درجه A ...,ورق ...,5.0,2293578,11467890,1032110,0,0,12500000,,82308
3,13990105,82517,1100140,احساني عليرضا ...,1-1-05-137,نئوپان 210*366 خام ممتاز گلستان درجه B ...,ورق ...,3.0,1788991,5366973,483028,0,0,5850001,,82309
4,13990105,82518,1101464,مطهري مهدي ...,1-1-01-294,ام دي اف 183*366 سفيد صابوني كيميا چوب ...,ورق ...,2.0,3669725,7339450,660551,0,0,8000001,,82310

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28252 entries, 0 to 28273
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              28252 non-null  int64
 1   ID                28252 non-null  int64
 2   Customer_ID       28252 non-null  int64
 3   Customer_Name     28252 non-null  object
 4   Item_Code         28252 non-null  object
 5   Description       28252 non-null  object
 6   Unit              28252 non-null  object
 7   Quantity          28252 non-null  float64
 8   Unit Price        28252 non-null  int64
 9   Amount            28252 non-null  int64
 10  Tax               28252 non-null  int64
 11  Discount          28252 non-null  int64
 12  Duties            28252 non-null  int64
 13  Net Amount        28252 non-null  int64
 14  Payment Date      28252 non-null  object
 15  Warehouse Serial  28252 non-null  int64
dtypes: float64(1), int64(10), object(5)
memory usage: 3.7+ MB

In [ ]:
wood1 = sales.loc[: , ['Customer_Name' , 'date' , 'Net Amount']].copy()

wood1 .head()

                                       Customer_Name      date  Net Amount
0  ابوالفضل تام                                  ...  13990105    12750003
1  ابوالفضل تام                                  ...  13990105     1299999
2  ابوالفضل تام                                  ...  13990105    12500000
3  احساني عليرضا                                 ...  13990105     5850001
4  مطهري مهدي                                    ...  13990105     8000001

In [ ]:
wood1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28252 entries, 0 to 28273
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_Name  28252 non-null  object
 1   date           28252 non-null  int64
 2   Net Amount     28252 non-null  int64
dtypes: int64(2), object(1)
memory usage: 882.9+ KB

In [ ]:
import jdatetime as jdt
import jalali_pandas

In [ ]:
def to_jalali_date(column, year_dir='L'): 
    if column.dtype == 'object':
        if '/' in column[0]:
            mod_col = [x.split('/') for x in column]
        elif '-' in column[0]:
            mod_col = [x.split('-') for x in column]
        elif '.' in column[0]:
            mod_col = [x.split('.') for x in column]
    
    elif column.dtype == 'int64':
        str_col = column.astype('str')
        if len(str(column[0])) == 8:
            if year_dir == 'L':
                mod_col = [[x[0:4], x[4:6], x[6:]] for x in str_col]
            elif year_dir == 'R':
                mod_col = [[x[0:2], x[2:4], x[4:]] for x in str_col]
        elif len(str(column[0])) == 6:
            mod_col = [[x[0:2], x[2:4], x[4:]] for x in str_col]

    if year_dir == 'L':
        year = [i[0] for i in mod_col]
        month = [i[1] for i in mod_col]
        day = [i[2] for i in mod_col]
    else:
        year = [i[2] for i in mod_col]
        month = [i[1] for i in mod_col]
        day = [i[0] for i in mod_col]

    if len(year[0]) == 2:
        if int(year[0]) < 50:
            year = ['14'+j for j in year]
        elif int(year[0]) > 50:
            year = ['13'+j for j in year]

    new_correct_date = []
    for n in range(len(year)):
        y = int(year[n])
        m = int(month[n])
        d = int(day[n])
        new_correct_date.append(jdt.date(y, m, d))  # jdt.datetime
    return new_correct_date

In [ ]:
wood1['Inv_Date'] = to_jalali_date(wood1['date'])
wood1.sample(5)

,Customer_Name,date,Net Amount,Inv_Date
27315,غلامي محمد ...,13991223,6199998,1399-12-23
47,حاج ابوئي ...,13990109,5100000,1399-01-09
3282,محمد حسين حاجي عليزاده ...,13990228,34759993,1399-02-28
6373,اصغري محمد ...,13990407,69749983,1399-04-07
17760,مصطفي نوحي ...,13990818,3900001,1399-08-18

In [ ]:
wood1['year']    = wood1.Inv_Date.jalali.year
wood1['month']   = wood1.Inv_Date.jalali.month
wood1['day'] = wood1.Inv_Date.jalali.day

wood1 .sample(5)

,Customer_Name,date,Net Amount,Inv_Date,year,month,day
6901,مرتضوي رضا ...,13990411,1299999,1399-04-11,1399,4,11
14687,اسماعيلي بخش ...,13990706,4550000,1399-07-06,1399,7,6
4580,علي بوكان ...,13990318,5439999,1399-03-18,1399,3,18
19880,غلامي محمد ...,13990918,30999999,1399-09-18,1399,9,18
10800,فخار زاده هادي ...,13990522,32000002,1399-05-22,1399,5,22

In [ ]:
best_customer = wood1.groupby(
                            ['Customer_Name' , 'year' , 'month']
                        
                            )['Net Amount'].sum().reset_index()

best_customer.head(12)

                                        Customer_Name  year  month  Net Amount
0   آزادي اعتماد                                  ...  1399      2   177030108
1   آزادي اعتماد                                  ...  1399      3  1199500147
2   آزادي اعتماد                                  ...  1399      4   379260002
3   آزادي اعتماد                                  ...  1399      5  1383279970
4   آزادي اعتماد                                  ...  1399      6   154000014
5   آزادي اعتماد                                  ...  1399     10   137339986
6   آزادي اعتماد                                  ...  1399     11  1136500057
7   آسيابان سعيد                                  ...  1399      1    91780011
8   آسيابان سعيد                                  ...  1399      2   112560006
9   آسيابان سعيد                                  ...  1399      3    34179994
10  آسيابان سعيد                                  ...  1399      4   151199987
11  آسيابان سعيد                                  ...  1399      5   102229999

In [ ]:
wood1.groupby(['Customer_Name' , 'year' , 'month'] ) .ngroups

2352

In [ ]:
top_customer_month =best_customer.loc[best_customer.groupby( ['Customer_Name' , 'year' , 'month'])['Net Amount'].idxmax()]
top_customer_month

,Customer_Name,year,month,Net Amount
0,آزادي اعتماد ...,1399,2,177030108
1,آزادي اعتماد ...,1399,3,1199500147
2,آزادي اعتماد ...,1399,4,379260002
3,آزادي اعتماد ...,1399,5,1383279970
4,آزادي اعتماد ...,1399,6,154000014
...,...,...,...,...
2347,گلزار محسن ...,1399,9,226540006
2348,گلزار محسن ...,1399,10,555800008
2349,گلزار محسن ...,1399,11,321000002
2350,گلزار محسن ...,1399,12,278550006
2351,گنجي حسين ...,1399,4,25110000

In [ ]:
sort = top_customer_month.sort_values( by= ['month' , 'Net Amount'] , ascending= [True , False])
sort.reset_index()

,index,Customer_Name,year,month,Net Amount
0,240,امير طلايي ...,1399,1,2198479667
1,471,حاج ابوئي ...,1399,1,1926316552
2,1971,مصطفي نوحي ...,1399,1,1267660110
3,1895,مختاري احمد ...,1399,1,1191720129
4,554,حسين آزادي ...,1399,1,1096420011
...,...,...,...,...,...
2347,1402,علي صفر حسيني ...,1399,12,3099999
2348,1888,محمدي يوسف ...,1399,12,2250001
2349,237,امير حسام بهادري پسند ...,1399,12,600001
2350,873,رجبيون ميلاد ...,1399,12,300000
2351,2025,منصوري جامع كيا ...,1399,12,200000

In [ ]:
top_customer_1_month = top_customer_month.groupby(['year', 'month']).first().reset_index()
top_customer_1_month

    year  month                                      Customer_Name  Net Amount
0   1399      1  آسيابان سعيد                                  ...    91780011
1   1399      2  آزادي اعتماد                                  ...   177030108
2   1399      3  آزادي اعتماد                                  ...  1199500147
3   1399      4  آزادي اعتماد                                  ...   379260002
4   1399      5  آزادي اعتماد                                  ...  1383279970
5   1399      6  آزادي اعتماد                                  ...   154000014
6   1399      7  آسيابان سعيد                                  ...   376949960
7   1399      8  آقاي صالحي روكش                               ...   418499965
8   1399      9  آسيابان سعيد                                  ...   337799987
9   1399     10  آزادي اعتماد                                  ...   137339986
10  1399     11  آزادي اعتماد                                  ...  1136500057
11  1399     12  آقا محمدي سعيد                                ...  3480449280

# سه محصول پرفروش به همراه سود خالص

In [12]:
sales.head()

,date,ID,Customer_ID,Customer_Name,Item_Code,Description,Unit,Quantity,Unit Price,Amount,Tax,Discount,Duties,Net Amount,Payment Date,Warehouse Serial
0,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-706,ملامينه 210*280 كد 361 سفيد صابوني كيميا ...,ورق ...,5.0,2339450,11697250,1052753,0,0,12750003,,82308
1,13990105,82516,1101328,ابوالفضل تام ...,1-1-01-505,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,ورق ...,2.0,596330,1192660,107339,0,0,1299999,,82308
2,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-023,ملامينه 204*260 كد 79 آنتيك سويز درجه A ...,ورق ...,5.0,2293578,11467890,1032110,0,0,12500000,,82308
3,13990105,82517,1100140,احساني عليرضا ...,1-1-05-137,نئوپان 210*366 خام ممتاز گلستان درجه B ...,ورق ...,3.0,1788991,5366973,483028,0,0,5850001,,82309
4,13990105,82518,1101464,مطهري مهدي ...,1-1-01-294,ام دي اف 183*366 سفيد صابوني كيميا چوب ...,ورق ...,2.0,3669725,7339450,660551,0,0,8000001,,82310

In [19]:
sales.columns

Index(['date', 'ID', 'Customer_ID', 'Customer_Name', 'Item_Code',
       'Description', 'Unit', 'Quantity', 'Unit Price', 'Amount', 'Tax',
       'Discount', 'Duties', 'Net Amount', 'Payment Date', 'Warehouse Serial'],
      dtype='object')

In [13]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28274 entries, 0 to 28273
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              28274 non-null  int64
 1   ID                28274 non-null  int64
 2   Customer_ID       28274 non-null  int64
 3   Customer_Name     28274 non-null  object
 4   Item_Code         28274 non-null  object
 5   Description       28274 non-null  object
 6   Unit              28274 non-null  object
 7   Quantity          28274 non-null  float64
 8   Unit Price        28274 non-null  int64
 9   Amount            28274 non-null  int64
 10  Tax               28274 non-null  int64
 11  Discount          28274 non-null  int64
 12  Duties            28274 non-null  int64
 13  Net Amount        28274 non-null  int64
 14  Payment Date      28274 non-null  object
 15  Warehouse Serial  28274 non-null  int64
dtypes: float64(1), int64(10), object(5)
memory usage: 3.5+ MB

In [14]:
sales.duplicated().sum()

22

In [16]:
sales.drop_duplicates(inplace=True)

In [17]:
sales.duplicated().sum()

0

In [18]:
sales.isnull().sum().sum()

0

In [21]:
# net profit

sales['Net Profit'] = (sales['Quantity'] * sales['Unit Price']) - (sales['Tax'] + sales['Discount'] + sales['Duties'])
sales.head()

,date,ID,Customer_ID,Customer_Name,Item_Code,Description,Unit,Quantity,Unit Price,Amount,Tax,Discount,Duties,Net Amount,Payment Date,Warehouse Serial,Net Profit
0,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-706,ملامينه 210*280 كد 361 سفيد صابوني كيميا ...,ورق ...,5.0,2339450,11697250,1052753,0,0,12750003,,82308,10644497.0
1,13990105,82516,1101328,ابوالفضل تام ...,1-1-01-505,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,ورق ...,2.0,596330,1192660,107339,0,0,1299999,,82308,1085321.0
2,13990105,82516,1101328,ابوالفضل تام ...,1-1-04-023,ملامينه 204*260 كد 79 آنتيك سويز درجه A ...,ورق ...,5.0,2293578,11467890,1032110,0,0,12500000,,82308,10435780.0
3,13990105,82517,1100140,احساني عليرضا ...,1-1-05-137,نئوپان 210*366 خام ممتاز گلستان درجه B ...,ورق ...,3.0,1788991,5366973,483028,0,0,5850001,,82309,4883945.0
4,13990105,82518,1101464,مطهري مهدي ...,1-1-01-294,ام دي اف 183*366 سفيد صابوني كيميا چوب ...,ورق ...,2.0,3669725,7339450,660551,0,0,8000001,,82310,6678899.0

In [24]:
sales.Description.str.strip()

0          ملامينه 210*280 كد 361 سفيد صابوني كيميا
1         اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A
2           ملامينه 204*260 كد 79 آنتيك سويز درجه A
3            نئوپان 210*366 خام ممتاز گلستان درجه B
4            ام دي اف 183*366 سفيد صابوني كيميا چوب
                            ...
28269                     نئوپان 210*305 خام درجه 1
28270            ام دي اف 210*366 كد 60 ونگه درجه A
28271      ملامينه 210*366 كد 70 گردويي تيره درجه A
28272                         نئوپان 204*260 خام 2%
28273    ام دي اف 183*366 كد 946 نولا اكسترا درجه 1
Name: Description, Length: 28252, dtype: object

In [31]:
prudact_grp = sales.groupby('Description').agg(  { 'Net Profit' : 'sum' ,
                                    'Amount' : 'sum'}).reset_index()
prudact_grp.head()

,Description,Net Profit,Amount
0,ال دي اف 210*305 خام آرين سينا ...,9.339355e+09,10285275600
1,ام دي اف 122*244 خام خزر كاسپين A ...,1.872442e+10,20626615523
2,ام دي اف 122*244 خام درجه 1 آرين سينا ...,4.129103e+09,4538852062
3,ام دي اف 122*244 خام درجه 2 آرين سينا ...,2.027923e+09,2259037088
4,ام دي اف 122*244 خام پاركو B ...,2.132156e+09,2343028166

In [35]:
prudact_grp.sort_values(by='Amount' , ascending=False).reset_index()

,index,Description,Net Profit,Amount
0,572,ملامينه 210*366 كد 1 سفيد درجه A ...,4.219237e+10,46410735040
1,261,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,2.847184e+10,31327025305
2,411,ملامينه 125*280 كد 361 سفيد ...,2.364559e+10,26003734867
3,172,ام دي اف 210*280 سفيد صابوني درجه 1 كيميا ...,2.342346e+10,25781752190
4,1,ام دي اف 122*244 خام خزر كاسپين A ...,1.872442e+10,20626615523
...,...,...,...,...
732,295,زيرپالتي نئوپان 61*366 ...,7.513810e+05,825693
733,708,نئوپان 125*250 خام درجه 1 ...,6.678900e+05,733945
734,293,زيرپالتي نئوپان 244*280 ...,5.844100e+05,642208
735,216,ام دي اف 3 ميل 183*244 سفيد پرينتي ...,5.009180e+05,550459
736,284,زيرپالتي متفرقه ...,1.490000e+02,162

In [38]:
prudact_grp.loc[:2 , ['Description'	, 'Net Profit' ,	'Amount']]

,Description,Net Profit,Amount
0,ال دي اف 210*305 خام آرين سينا ...,9.339355e+09,10285275600
1,ام دي اف 122*244 خام خزر كاسپين A ...,1.872442e+10,20626615523
2,ام دي اف 122*244 خام درجه 1 آرين سينا ...,4.129103e+09,4538852062

In [26]:
sales.groupby('Description').ngroups

737

# پرفروش ترین محصول هر ماه با سود خالص

In [39]:
sales.columns

Index(['date', 'ID', 'Customer_ID', 'Customer_Name', 'Item_Code',
       'Description', 'Unit', 'Quantity', 'Unit Price', 'Amount', 'Tax',
       'Discount', 'Duties', 'Net Amount', 'Payment Date', 'Warehouse Serial',
       'Net Profit'],
      dtype='object')

In [46]:
product = sales.loc[: , ['Description' , 'date' , 'Net Profit' , 'Amount']].copy()

product.head()

,Description,date,Net Profit,Amount
0,ملامينه 210*280 كد 361 سفيد صابوني كيميا ...,13990105,10644497.0,11697250
1,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,13990105,1085321.0,1192660
2,ملامينه 204*260 كد 79 آنتيك سويز درجه A ...,13990105,10435780.0,11467890
3,نئوپان 210*366 خام ممتاز گلستان درجه B ...,13990105,4883945.0,5366973
4,ام دي اف 183*366 سفيد صابوني كيميا چوب ...,13990105,6678899.0,7339450

In [47]:
product.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28252 entries, 0 to 28273
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Description  28252 non-null  object
 1   date         28252 non-null  int64
 2   Net Profit   28252 non-null  float64
 3   Amount       28252 non-null  int64
dtypes: float64(1), int64(2), object(1)
memory usage: 2.1+ MB

In [48]:
import jdatetime as jdt
import jalali_pandas

In [49]:
def to_jalali_date(column, year_dir='L'): 
    if column.dtype == 'object':
        if '/' in column[0]:
            mod_col = [x.split('/') for x in column]
        elif '-' in column[0]:
            mod_col = [x.split('-') for x in column]
        elif '.' in column[0]:
            mod_col = [x.split('.') for x in column]
    
    elif column.dtype == 'int64':
        str_col = column.astype('str')
        if len(str(column[0])) == 8:
            if year_dir == 'L':
                mod_col = [[x[0:4], x[4:6], x[6:]] for x in str_col]
            elif year_dir == 'R':
                mod_col = [[x[0:2], x[2:4], x[4:]] for x in str_col]
        elif len(str(column[0])) == 6:
            mod_col = [[x[0:2], x[2:4], x[4:]] for x in str_col]

    if year_dir == 'L':
        year = [i[0] for i in mod_col]
        month = [i[1] for i in mod_col]
        day = [i[2] for i in mod_col]
    else:
        year = [i[2] for i in mod_col]
        month = [i[1] for i in mod_col]
        day = [i[0] for i in mod_col]

    if len(year[0]) == 2:
        if int(year[0]) < 50:
            year = ['14'+j for j in year]
        elif int(year[0]) > 50:
            year = ['13'+j for j in year]

    new_correct_date = []
    for n in range(len(year)):
        y = int(year[n])
        m = int(month[n])
        d = int(day[n])
        new_correct_date.append(jdt.date(y, m, d))  # jdt.datetime
    return new_correct_date

In [50]:
product['Inv_Date'] = to_jalali_date(product['date'])
product.sample(5)

,Description,date,Net Profit,Amount,Inv_Date
19412,پي وي سي 122*280 سفيد درجه 1 ...,13990909,7931192.0,8715596,1399-09-09
14064,ملامينه 125*280 كد 361 سفيد ...,13990630,4090825.0,4495412,1399-06-30
9158,ام دي اف 183*366 كد 778 سفيد متاليك براق نوين ...,13990505,6177982.0,6788991,1399-05-05
2471,چسب وانا ...,13990216,12773397.0,14036700,1399-02-16
3933,ملامينه 183*366 كد 1 سفيد موربيدا صابوني درجه ...,13990308,2487890.0,2733945,1399-03-08

In [51]:
product['year']    = product.Inv_Date.jalali.year
product['month']   = product.Inv_Date.jalali.month
product['day'] = product.Inv_Date.jalali.day

product .sample(5)

,Description,date,Net Profit,Amount,Inv_Date,year,month,day
9413,ملامينه 204*260 كد 85 لاركس درجه A ...,13990507,16029359.0,17614680,1399-05-07,1399,5,7
13057,ملامينه 210*366 كد 71 گردويي روشن درجه A ...,13990619,106361470.0,116880736,1399-06-19,1399,6,19
18193,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,13990822,7113026.0,7816512,1399-08-22,1399,8,22
24169,زيرپالتي ضايعات ...,13991115,2.0,2,1399-11-15,1399,11,15
2191,ملامينه 125*280 كد 323 گردويي تيره ...,13990213,12522938.0,13761470,1399-02-13,1399,2,13

In [66]:
best_product = product.groupby(
                            ['Description' , 'year' , 'month']
                        
                            ).agg({ 'Amount' : 'sum'   , 'Net Profit' : 'sum'}).reset_index()

best_product

,Description,year,month,Amount,Net Profit
0,ال دي اف 210*305 خام آرين سينا ...,1399,1,1083440490,9.832593e+08
1,ال دي اف 210*305 خام آرين سينا ...,1399,2,1906881055,1.735262e+09
2,ال دي اف 210*305 خام آرين سينا ...,1399,3,2227752341,2.012269e+09
3,ال دي اف 210*305 خام آرين سينا ...,1399,4,182064211,1.656784e+08
4,ال دي اف 210*305 خام آرين سينا ...,1399,6,2597247608,2.363495e+09
...,...,...,...,...,...
2960,چوب راش 7 سانت گريد AB ...,1399,4,725622935,6.603169e+08
2961,چوب راش 7 سانت گريد AB ...,1399,5,700733942,6.376620e+08
2962,چوب راش 7 سانت گريد C ...,1399,4,514345873,4.665578e+08
2963,چوب راش 7 سانت گريد C ...,1399,5,648919268,5.905165e+08
2964,چوب راش 7 سانت گريد C ...,1399,7,113875230,1.036265e+08

In [61]:
best_product.sort_values(by=['month' , 'year' , 'Amount' ] , ascending=[True , True ,False]).reset_index()

,index,Description,year,month,Amount,Net Profit
0,1716,ملامينه 125*280 كد 361 سفيد ...,1399,1,2011495372,1.828332e+09
1,2227,ملامينه 210*366 كد 1 سفيد درجه A ...,1399,1,1648844052,1.491565e+09
2,0,ال دي اف 210*305 خام آرين سينا ...,1399,1,1083440490,9.832593e+08
3,928,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,1399,1,1037247320,9.368822e+08
4,1505,ملامينه 125*280 كد 330 آنتيك طلائي ...,1399,1,998523030,9.056171e+08
...,...,...,...,...,...,...
2960,1116,زيرپالتي نئوپان 183*244 ...,1399,12,917439,8.348700e+05
2961,1008,زيرپالتي ام دي اف 122*280 ...,1399,12,596331,5.426610e+05
2962,1030,زيرپالتي ام دي اف 210*305 ...,1399,12,596330,5.426600e+05
2963,1074,زيرپالتي نئوپان 122*244 ...,1399,12,412846,3.756890e+05
2964,1094,زيرپالتي نئوپان 125*250 ...,1399,12,183486,1.669720e+05

In [69]:
top_product_month =best_product.loc[best_product.groupby( ['Description' , 'year' , 'month'])['Amount'].idxmax()]
top_product_month

,Description,year,month,Amount,Net Profit
0,ال دي اف 210*305 خام آرين سينا ...,1399,1,1083440490,9.832593e+08
1,ال دي اف 210*305 خام آرين سينا ...,1399,2,1906881055,1.735262e+09
2,ال دي اف 210*305 خام آرين سينا ...,1399,3,2227752341,2.012269e+09
3,ال دي اف 210*305 خام آرين سينا ...,1399,4,182064211,1.656784e+08
4,ال دي اف 210*305 خام آرين سينا ...,1399,6,2597247608,2.363495e+09
...,...,...,...,...,...
2960,چوب راش 7 سانت گريد AB ...,1399,4,725622935,6.603169e+08
2961,چوب راش 7 سانت گريد AB ...,1399,5,700733942,6.376620e+08
2962,چوب راش 7 سانت گريد C ...,1399,4,514345873,4.665578e+08
2963,چوب راش 7 سانت گريد C ...,1399,5,648919268,5.905165e+08
2964,چوب راش 7 سانت گريد C ...,1399,7,113875230,1.036265e+08

In [70]:
sort1 = top_product_month.sort_values( by= ['month' , 'Amount'] , ascending= [True , False])

sort1.reset_index()

,index,Description,year,month,Amount,Net Profit
0,1716,ملامينه 125*280 كد 361 سفيد ...,1399,1,2011495372,1.828332e+09
1,2227,ملامينه 210*366 كد 1 سفيد درجه A ...,1399,1,1648844052,1.491565e+09
2,0,ال دي اف 210*305 خام آرين سينا ...,1399,1,1083440490,9.832593e+08
3,928,اچ دي اف 3 ميل 210*244 سفيد پرينتي درجه A ...,1399,1,1037247320,9.368822e+08
4,1505,ملامينه 125*280 كد 330 آنتيك طلائي ...,1399,1,998523030,9.056171e+08
...,...,...,...,...,...,...
2960,1116,زيرپالتي نئوپان 183*244 ...,1399,12,917439,8.348700e+05
2961,1008,زيرپالتي ام دي اف 122*280 ...,1399,12,596331,5.426610e+05
2962,1030,زيرپالتي ام دي اف 210*305 ...,1399,12,596330,5.426600e+05
2963,1074,زيرپالتي نئوپان 122*244 ...,1399,12,412846,3.756890e+05
2964,1094,زيرپالتي نئوپان 125*250 ...,1399,12,183486,1.669720e+05

In [71]:
top_product_1_month = top_product_month.groupby(['year', 'month']).first().reset_index()
top_product_1_month

,year,month,Description,Amount,Net Profit
0,1399,1,ال دي اف 210*305 خام آرين سينا ...,1083440490,9.832593e+08
1,1399,2,ال دي اف 210*305 خام آرين سينا ...,1906881055,1.735262e+09
2,1399,3,ال دي اف 210*305 خام آرين سينا ...,2227752341,2.012269e+09
3,1399,4,ال دي اف 210*305 خام آرين سينا ...,182064211,1.656784e+08
4,1399,5,ام دي اف 122*244 خام خزر كاسپين A ...,4263761850,3.853585e+09
5,1399,6,ال دي اف 210*305 خام آرين سينا ...,2597247608,2.363495e+09
6,1399,7,ال دي اف 210*305 خام آرين سينا ...,1320412794,1.201576e+09
7,1399,8,ام دي اف 122*244 خام خزر كاسپين A ...,229908280,2.092165e+08
8,1399,9,ام دي اف 122*244 خام خزر كاسپين A ...,1764954140,1.595389e+09
9,1399,10,ال دي اف 210*305 خام آرين سينا ...,99587153,9.062431e+07
10,1399,11,ال دي اف 210*305 خام آرين سينا ...,777614720,7.062101e+08
11,1399,12,ال دي اف 210*305 خام آرين سينا ...,90275228,8.098165e+07