In [108]:
import pandas as pd
import numpy as np

# reading , clean data , rename columns

In [109]:
purchase = pd. read_excel('WoodInc-purchase.xlsx')
purchase.head(10)

,تاريخ,شماره,کد تأمین کننده,نام تأمین کننده,کد کالا,نام کالا,واحد,مقدار,في,مبلغ,ماليات,تخفيف,عوارض,مبلغ خالص,تاريخ تسويه,سريال انبار
0,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-04-015,ملامينه 204*260 كد 1 سفيد درجه A ...,ورق ...,315.0,1879000,-591885000,-53269650,0,0,-645154650,,536
1,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-04-022,ملامينه 204*260 كد 78 آنتيك لايت درجه A ...,ورق ...,45.0,2087000,-93915000,-8452350,0,0,-102367350,,536
2,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-02-003,زيرپالتي نئوپان 204*260 ...,ورق ...,8.0,1,-8,0,-8,0,0,,536
3,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-02-009,زيرپالتي ام دي اف 3ميل ...,ورق ...,8.0,1,-8,0,-8,0,0,,536
4,13990119,2,1100249,شركت پالار ...,1-1-04-131,ملامينه 210*366 كد 1 سفيد درجه A ...,ورق ...,140.0,2674000,-374360000,-33692400,0,0,-408052400,,537
5,13990119,2,1100249,شركت پالار ...,1-1-04-198,ملامينه 210*366 كد 85 لاركس درجه A ...,ورق ...,28.0,2972000,-83216000,-7489440,0,0,-90705440,,537
6,13990119,2,1100249,شركت پالار ...,1-1-04-177,ملامينه 210*366 كد 96 برجسته درجه A ...,ورق ...,28.0,2972000,-83216000,-7489440,0,0,-90705440,,537
7,13990119,2,1100249,شركت پالار ...,1-1-04-631,ملامينه هايگلاس 210*366 كد 157 نقره اي متاليك ...,ورق ...,28.0,3236000,-90608000,-8154720,0,0,-98762720,,537
8,13990119,2,1100249,شركت پالار ...,1-1-04-632,ملامينه هايگلاس 210*366 كد 158 متاليك درجه A ...,ورق ...,28.0,3236000,-90608000,-8154720,0,0,-98762720,,537
9,13990119,2,1100249,شركت پالار ...,1-1-02-009,زيرپالتي ام دي اف 3ميل ...,ورق ...,9.0,1,-9,0,-9,0,0,,537

In [110]:
purchase.columns

Index(['تاريخ', 'شماره', 'کد تأمین کننده', 'نام تأمین کننده', 'کد کالا',
       'نام کالا', 'واحد', 'مقدار', 'في', 'مبلغ', 'ماليات', 'تخفيف', 'عوارض',
       'مبلغ خالص', 'تاريخ تسويه', 'سريال انبار'],
      dtype='object')

In [111]:
purchase.columns = [ 'date' , 'ID' , 'Vendor_code','Vendor_Name' , 'Item_Code' , 'Description' , 'Unit' , 'Quantity','Unit Price' , 'Amount' , 'Tax' ,'Discount',
                    'Duties' , 'Net Amount' , 'Payment Date' , 'Warehouse Serial' ] 

purchase.head()

,date,ID,Vendor_code,Vendor_Name,Item_Code,Description,Unit,Quantity,Unit Price,Amount,Tax,Discount,Duties,Net Amount,Payment Date,Warehouse Serial
0,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-04-015,ملامينه 204*260 كد 1 سفيد درجه A ...,ورق ...,315.0,1879000,-591885000,-53269650,0,0,-645154650,,536
1,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-04-022,ملامينه 204*260 كد 78 آنتيك لايت درجه A ...,ورق ...,45.0,2087000,-93915000,-8452350,0,0,-102367350,,536
2,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-02-003,زيرپالتي نئوپان 204*260 ...,ورق ...,8.0,1,-8,0,-8,0,0,,536
3,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-02-009,زيرپالتي ام دي اف 3ميل ...,ورق ...,8.0,1,-8,0,-8,0,0,,536
4,13990119,2,1100249,شركت پالار ...,1-1-04-131,ملامينه 210*366 كد 1 سفيد درجه A ...,ورق ...,140.0,2674000,-374360000,-33692400,0,0,-408052400,,537

In [112]:
purchase.replace(["NaN", "None", "null", "", " "], np.nan, inplace=True)

In [113]:
purchase.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2232 entries, 0 to 2231
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              2232 non-null   int64
 1   ID                2232 non-null   int64
 2   Vendor_code       2232 non-null   int64
 3   Vendor_Name       2232 non-null   object
 4   Item_Code         2232 non-null   object
 5   Description       2232 non-null   object
 6   Unit              2232 non-null   object
 7   Quantity          2232 non-null   float64
 8   Unit Price        2232 non-null   int64
 9   Amount            2232 non-null   int64
 10  Tax               2232 non-null   int64
 11  Discount          2232 non-null   int64
 12  Duties            2232 non-null   int64
 13  Net Amount        2232 non-null   int64
 14  Payment Date      2232 non-null   object
 15  Warehouse Serial  2232 non-null   int64
dtypes: float64(1), int64(10), object(5)
memory usage: 279.1+ KB

In [114]:
purchase.isnull().sum(axis = 0)

date                0
ID                  0
Vendor_code         0
Vendor_Name         0
Item_Code           0
Description         0
Unit                0
Quantity            0
Unit Price          0
Amount              0
Tax                 0
Discount            0
Duties              0
Net Amount          0
Payment Date        0
Warehouse Serial    0
dtype: int64

In [115]:
purchase.isnull().sum().sum()

0

In [116]:
purchase.duplicated(keep=False).sum()

22

In [117]:
dups        = purchase.duplicated(keep = False) 
dups_purchase = purchase.loc[dups]
dups_purchase

,date,ID,Vendor_code,Vendor_Name,Item_Code,Description,Unit,Quantity,Unit Price,Amount,Tax,Discount,Duties,Net Amount,Payment Date,Warehouse Serial
249,13990317,64,1101747,شركت آرين تخته ...,1-1-02-032,زيرپالتي ام دي اف 210*305 ...,ورق ...,6.0,1,-6,0,-6,0,0,,619
250,13990317,64,1101747,شركت آرين تخته ...,1-1-02-032,زيرپالتي ام دي اف 210*305 ...,ورق ...,6.0,1,-6,0,-6,0,0,,619
352,13990326,85,1101124,شركت افرا چوب ...,1-1-01-332,ام دي اف 183*366 كد 104 آنتراسيد ساليد(افرا) ...,ورق ...,32.0,6837523,-218800736,-19692066,0,0,-238492802,,639
353,13990326,85,1101124,شركت افرا چوب ...,1-1-01-332,ام دي اف 183*366 كد 104 آنتراسيد ساليد(افرا) ...,ورق ...,32.0,6837523,-218800736,-19692066,0,0,-238492802,,639
356,13990326,85,1101124,شركت افرا چوب ...,1-1-02-002,زيرپالتي ام دي اف 122*280 ...,ورق ...,2.0,1,-2,0,-2,0,0,,639
357,13990326,85,1101124,شركت افرا چوب ...,1-1-02-002,زيرپالتي ام دي اف 122*280 ...,ورق ...,2.0,1,-2,0,-2,0,0,,639
833,13990515,167,1100127,شركت نوين چوب فاليز ...,1-1-02-035,زير پالتي نئوپان 183*366 ...,ورق ...,1.0,1,-1,0,-1,0,0,,761
836,13990515,167,1100127,شركت نوين چوب فاليز ...,1-1-02-035,زير پالتي نئوپان 183*366 ...,ورق ...,1.0,1,-1,0,-1,0,0,,761
1260,13990719,267,1101747,شركت آرين تخته ...,1-1-02-036,زير پالتي ام دي اف 183*366 ...,ورق ...,6.0,1,-6,0,-6,0,0,,899
1261,13990719,267,1101747,شركت آرين تخته ...,1-1-02-036,زير پالتي ام دي اف 183*366 ...,ورق ...,6.0,1,-6,0,-6,0,0,,899
1416,13990819,307,1100251,شركت تخته فشرده شمال ...,1-1-02-032,زيرپالتي ام دي اف 210*305 ...,ورق ...,6.0,1,-6,0,-6,0,0,,946
1417,13990819,307,1100251,شركت تخته فشرده شمال ...,1-1-02-032,زيرپالتي ام دي اف 210*305 ...,ورق ...,6.0,1,-6,0,-6,0,0,,946
1621,13990909,336,1100252,شركت خزر كاسپين ...,1-1-02-012,زيرپالتي ام دي اف 122*244 ...,ورق ...,9.0,1,-9,0,-9,0,0,,981
1622,13990909,336,1100252,شركت خزر كاسپين ...,1-1-02-012,زيرپالتي ام دي اف 122*244 ...,ورق ...,27.0,1,-27,0,-27,0,0,,981
1623,13990909,336,1100252,شركت خزر كاسپين ...,1-1-02-012,زيرپالتي ام دي اف 122*244 ...,ورق ...,9.0,1,-9,0,-9,0,0,,981
1624,13990909,336,1100252,شركت خزر كاسپين ...,1-1-02-012,زيرپالتي ام دي اف 122*244 ...,ورق ...,27.0,1,-27,0,-27,0,0,,981
1816,13991010,381,1101124,شركت افرا چوب ...,1-1-02-036,زير پالتي ام دي اف 183*366 ...,ورق ...,1.0,1,-1,0,-1,0,0,,1029
1817,13991010,381,1101124,شركت افرا چوب ...,1-1-02-036,زير پالتي ام دي اف 183*366 ...,ورق ...,1.0,1,-1,0,-1,0,0,,1029
1910,13991025,406,1100250,شركت راش بينه ...,1-1-02-036,زير پالتي ام دي اف 183*366 ...,ورق ...,1.0,1,-1,0,-1,0,0,,1062
1912,13991025,406,1100250,شركت راش بينه ...,1-1-02-036,زير پالتي ام دي اف 183*366 ...,ورق ...,1.0,1,-1,0,-1,0,0,,1062
2104,13991209,462,1102155,شركت پارت چوب شاد ...,1-1-02-036,زير پالتي ام دي اف 183*366 ...,ورق ...,6.0,1,-6,0,-6,0,0,,1122
2105,13991209,462,1102155,شركت پارت چوب شاد ...,1-1-02-036,زير پالتي ام دي اف 183*366 ...,ورق ...,6.0,1,-6,0,-6,0,0,,1122

In [118]:
purchase.drop_duplicates(inplace=True)

In [119]:
purchase[['Amount' , 'Tax' , 'Discount'	, 'Duties' ,	'Net Amount' ]] = purchase [ ['Amount' , 'Tax' , 'Discount'	, 'Duties' ,	'Net Amount' ]].abs()

In [120]:
purchase.columns

Index(['date', 'ID', 'Vendor_code', 'Vendor_Name', 'Item_Code', 'Description',
       'Unit', 'Quantity', 'Unit Price', 'Amount', 'Tax', 'Discount', 'Duties',
       'Net Amount', 'Payment Date', 'Warehouse Serial'],
      dtype='object')

In [121]:
purchase.nunique()

date                211
ID                  500
Vendor_code          26
Vendor_Name          26
Item_Code           556
Description         556
Unit                  5
Quantity            176
Unit Price          315
Amount              771
Tax                 714
Discount             55
Duties                1
Net Amount          754
Payment Date          1
Warehouse Serial    510
dtype: int64

In [122]:
purchase.groupby(by='Vendor_Name').nunique()

,date,ID,Vendor_code,Item_Code,Description,Unit,Quantity,Unit Price,Amount,Tax,Discount,Duties,Net Amount,Payment Date,Warehouse Serial
Vendor_Name,,,,,,,,,,,,,,,
اتحاديه سراسري درودگران,2,2,1,11,11,1,5,4,7,6,3,1,6,1,2
خوش چسب كرمان,7,7,1,4,4,2,5,10,10,10,10,1,10,1,7
زاگرس چوب سام,11,11,1,10,10,1,17,12,24,12,14,1,12,1,12
سندل چوب,12,12,1,17,17,1,8,9,14,16,3,1,16,1,12
شركت آرين تخته,7,7,1,6,6,1,8,7,12,10,7,1,10,1,8
شركت آرين سينا,3,3,1,4,4,1,4,2,4,4,2,1,4,1,3
شركت آرين شيمي,1,1,1,3,3,1,2,2,2,2,2,1,2,1,1
شركت آرين مريم,4,4,1,4,4,1,7,5,9,5,6,1,5,1,4
شركت احسان كار اصفهان,4,4,1,6,6,1,10,8,12,9,5,1,10,1,4
شركت افرا چوب,2,2,1,19,19,1,19,6,23,17,8,1,17,1,2
شركت تخته فشرده آريانا(پانيذ),2,2,1,3,3,1,4,3,4,3,3,1,3,1,2
شركت تخته فشرده شمال,41,66,1,110,110,1,50,42,121,108,15,1,108,1,67
شركت تخته فشرده ممتاز گلستان,5,5,1,1,1,1,1,2,2,2,1,1,2,1,5
شركت خزر كاسپين,20,20,1,5,5,1,16,22,28,25,5,1,25,1,23
شركت راش بينه,82,142,1,84,84,1,38,38,136,125,10,1,133,1,143
شركت روكش آريا پويا,18,19,1,28,28,1,46,28,54,41,16,1,41,1,19
شركت صنايع چسب نوين گام,4,4,1,1,1,1,1,3,3,3,1,1,3,1,4
شركت ملامين سازه پويا,8,8,1,58,58,1,31,9,71,60,13,1,60,1,8
شركت نوين چوب فاليز,15,16,1,107,107,2,43,52,106,80,28,1,80,1,16
شركت پارت چوب شاد,4,4,1,5,5,1,8,5,9,5,7,1,5,1,4
شركت پالار,71,120,1,123,123,1,63,42,186,173,21,1,175,1,120
شركت پويا چوب,16,22,1,4,4,1,3,7,7,7,2,1,7,1,22
شركت چوب گستر كانيار,1,1,1,3,3,1,4,2,4,2,4,1,2,1,2
كيميا روكش گرگان,14,14,1,5,5,1,9,7,13,12,4,1,12,1,15
يالماز اورمان(ياشار),1,1,1,4,4,1,26,4,26,1,1,1,26,1,2
گروه صنعتي بازرگاني خادم/ ولي اله رضايي(آوا),3,3,1,7,7,1,9,5,9,5,6,1,5,1,3

In [123]:
purchase.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2221 entries, 0 to 2231
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              2221 non-null   int64
 1   ID                2221 non-null   int64
 2   Vendor_code       2221 non-null   int64
 3   Vendor_Name       2221 non-null   object
 4   Item_Code         2221 non-null   object
 5   Description       2221 non-null   object
 6   Unit              2221 non-null   object
 7   Quantity          2221 non-null   float64
 8   Unit Price        2221 non-null   int64
 9   Amount            2221 non-null   int64
 10  Tax               2221 non-null   int64
 11  Discount          2221 non-null   int64
 12  Duties            2221 non-null   int64
 13  Net Amount        2221 non-null   int64
 14  Payment Date      2221 non-null   object
 15  Warehouse Serial  2221 non-null   int64
dtypes: float64(1), int64(10), object(5)
memory usage: 295.0+ KB

In [124]:
#purchase.date   = pd.to_datetime(purchase.date)

In [125]:
purchase.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2221 entries, 0 to 2231
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              2221 non-null   int64
 1   ID                2221 non-null   int64
 2   Vendor_code       2221 non-null   int64
 3   Vendor_Name       2221 non-null   object
 4   Item_Code         2221 non-null   object
 5   Description       2221 non-null   object
 6   Unit              2221 non-null   object
 7   Quantity          2221 non-null   float64
 8   Unit Price        2221 non-null   int64
 9   Amount            2221 non-null   int64
 10  Tax               2221 non-null   int64
 11  Discount          2221 non-null   int64
 12  Duties            2221 non-null   int64
 13  Net Amount        2221 non-null   int64
 14  Payment Date      2221 non-null   object
 15  Warehouse Serial  2221 non-null   int64
dtypes: float64(1), int64(10), object(5)
memory usage: 295.0+ KB

In [126]:
#purchase['Vendor_Name'] = purchase['Vendor_Name'].str.strip()
purchase.Vendor_Name.str.strip()

0       شركت تخته فشرده شمال
1       شركت تخته فشرده شمال
2       شركت تخته فشرده شمال
3       شركت تخته فشرده شمال
4                 شركت پالار
                ...
2227           شركت راش بينه
2228           شركت راش بينه
2229           شركت راش بينه
2230           شركت راش بينه
2231           شركت راش بينه
Name: Vendor_Name, Length: 2221, dtype: object

In [127]:
purchase.head()

,date,ID,Vendor_code,Vendor_Name,Item_Code,Description,Unit,Quantity,Unit Price,Amount,Tax,Discount,Duties,Net Amount,Payment Date,Warehouse Serial
0,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-04-015,ملامينه 204*260 كد 1 سفيد درجه A ...,ورق ...,315.0,1879000,591885000,53269650,0,0,645154650,,536
1,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-04-022,ملامينه 204*260 كد 78 آنتيك لايت درجه A ...,ورق ...,45.0,2087000,93915000,8452350,0,0,102367350,,536
2,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-02-003,زيرپالتي نئوپان 204*260 ...,ورق ...,8.0,1,8,0,8,0,0,,536
3,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-02-009,زيرپالتي ام دي اف 3ميل ...,ورق ...,8.0,1,8,0,8,0,0,,536
4,13990119,2,1100249,شركت پالار ...,1-1-04-131,ملامينه 210*366 كد 1 سفيد درجه A ...,ورق ...,140.0,2674000,374360000,33692400,0,0,408052400,,537

# جمع کل فروش هر تامین کننده

In [128]:
vendor_sales = purchase.groupby('Vendor_Name')['Net Amount'].sum().reset_index()
vendor_sales.head(10)

                                         Vendor_Name   Net Amount
0  اتحاديه سراسري درودگران                       ...   1869692861
1  خوش چسب كرمان                                 ...   4639974391
2  زاگرس چوب سام                                 ...  15731928319
3  سندل چوب                                      ...  17629202086
4  شركت آرين تخته                                ...   9255260369
5  شركت آرين سينا                                ...   3965751360
6  شركت آرين شيمي                                ...   1739208779
7  شركت آرين مريم                                ...   4499053480
8  شركت احسان كار اصفهان                         ...   5113000739
9  شركت افرا چوب                                 ...   6100387332

## ترتیب سه تامین کننده برا اساس میزان فروش

In [129]:
# ترتیب سه تامین کننده برا اساس میزان فروش  


top_vendors = vendor_sales.sort_values(ascending= False , by = 'Net Amount')

top_vendors.reset_index()

    index                                        Vendor_Name    Net Amount
0      14  شركت راش بينه                                 ...  188564083823
1      20  شركت پالار                                    ...  173842152375
2      11  شركت تخته فشرده شمال                          ...  103193429390
3      15  شركت روكش آريا پويا                           ...   36595766438
4      18  شركت نوين چوب فاليز                           ...   33460968105
5      23  كيميا روكش گرگان                              ...   31649202645
6      13  شركت خزر كاسپين                               ...   29407055875
7      17  شركت ملامين سازه پويا                         ...   20473621510
8       3  سندل چوب                                      ...   17629202086
9      21  شركت پويا چوب                                 ...   16346298360
10      2  زاگرس چوب سام                                 ...   15731928319
11      4  شركت آرين تخته                                ...    9255260369
12     19  شركت پارت چوب شاد                             ...    6203160240
13      9  شركت افرا چوب                                 ...    6100387332
14      8  شركت احسان كار اصفهان                         ...    5113000739
15     12  شركت تخته فشرده ممتاز گلستان                  ...    4838400303
16     22  شركت چوب گستر كانيار                          ...    4781001600
17      1  خوش چسب كرمان                                 ...    4639974391
18      7  شركت آرين مريم                                ...    4499053480
19      5  شركت آرين سينا                                ...    3965751360
20     24  يالماز اورمان(ياشار)                          ...    3707340215
21     25  گروه صنعتي بازرگاني خادم/ ولي اله رضايي(آوا)  ...    2941601770
22     10  شركت تخته فشرده آريانا(پانيذ)                 ...    2575801445
23      0  اتحاديه سراسري درودگران                       ...    1869692861
24      6  شركت آرين شيمي                                ...    1739208779
25     16  شركت صنايع چسب نوين گام                       ...    1360570700

###  کل فروش شرکت

In [130]:
total_sale = vendor_sales['Net Amount'].sum()
total_sale

730483914510

#### سهم هر یک از کل خرید شرکت

In [131]:

vendor_sale_share = (purchase.groupby('Vendor_Name' )['Net Amount'].sum()/ total_sale) * 100

In [132]:
vendor_sale_share_df = vendor_sale_share.reset_index()

vendor_sale_share_df.columns = ['Vendor_Name','Share_Total_Sales']
vendor_sale_share_df.head(3)

                                         Vendor_Name  Share_Total_Sales
0  اتحاديه سراسري درودگران                       ...           0.255953
1  خوش چسب كرمان                                 ...           0.635192
2  زاگرس چوب سام                                 ...           2.153631

In [133]:
vendor_sale_share_df.sort_values(ascending= False , by = 'Share_Total_Sales')

                                          Vendor_Name  Share_Total_Sales
14  شركت راش بينه                                 ...          25.813585
20  شركت پالار                                    ...          23.798218
11  شركت تخته فشرده شمال                          ...          14.126722
15  شركت روكش آريا پويا                           ...           5.009798
18  شركت نوين چوب فاليز                           ...           4.580658
23  كيميا روكش گرگان                              ...           4.332635
13  شركت خزر كاسپين                               ...           4.025695
17  شركت ملامين سازه پويا                         ...           2.802748
3   سندل چوب                                      ...           2.413359
21  شركت پويا چوب                                 ...           2.237736
2   زاگرس چوب سام                                 ...           2.153631
4   شركت آرين تخته                                ...           1.267004
19  شركت پارت چوب شاد                             ...           0.849185
9   شركت افرا چوب                                 ...           0.835116
8   شركت احسان كار اصفهان                         ...           0.699947
12  شركت تخته فشرده ممتاز گلستان                  ...           0.662355
22  شركت چوب گستر كانيار                          ...           0.654498
1   خوش چسب كرمان                                 ...           0.635192
7   شركت آرين مريم                                ...           0.615900
5   شركت آرين سينا                                ...           0.542894
24  يالماز اورمان(ياشار)                          ...           0.507518
25  گروه صنعتي بازرگاني خادم/ ولي اله رضايي(آوا)  ...           0.402692
10  شركت تخته فشرده آريانا(پانيذ)                 ...           0.352616
0   اتحاديه سراسري درودگران                       ...           0.255953
6   شركت آرين شيمي                                ...           0.238090
16  شركت صنايع چسب نوين گام                       ...           0.186256

In [134]:
top_vendors.to_excel('top_vendor.xlsx')
vendor_sale_share_df.to_excel('sale_share.xlsx')

In [135]:
top_vendor1 = pd.read_excel('top_vendor.xlsx')
sale_share1 = pd.read_excel('sale_share.xlsx')

In [136]:
top_vendor1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   26 non-null     int64
 1   Vendor_Name  26 non-null     object
 2   Net Amount   26 non-null     int64
dtypes: int64(2), object(1)
memory usage: 756.0+ bytes

In [137]:
top_vendor1.head()
top_vendor1 = top_vendor1.drop('Unnamed: 0' , axis=1)

In [138]:
top_vendor1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Vendor_Name  26 non-null     object
 1   Net Amount   26 non-null     int64
dtypes: int64(1), object(1)
memory usage: 548.0+ bytes

In [139]:
merge_data = pd.merge( left = top_vendor1 ,
                        right= sale_share1 ,
                        on = 'Vendor_Name' , 
                        how = 'inner' , 
                        
                        )
merge_data

,Vendor_Name,Net Amount,Unnamed: 0,Share_Total_Sales
0,شركت راش بينه ...,188564083823,14,25.813585
1,شركت پالار ...,173842152375,20,23.798218
2,شركت تخته فشرده شمال ...,103193429390,11,14.126722
3,شركت روكش آريا پويا ...,36595766438,15,5.009798
4,شركت نوين چوب فاليز ...,33460968105,18,4.580658
5,كيميا روكش گرگان ...,31649202645,23,4.332635
6,شركت خزر كاسپين ...,29407055875,13,4.025695
7,شركت ملامين سازه پويا ...,20473621510,17,2.802748
8,سندل چوب ...,17629202086,3,2.413359
9,شركت پويا چوب ...,16346298360,21,2.237736
10,زاگرس چوب سام ...,15731928319,2,2.153631
11,شركت آرين تخته ...,9255260369,4,1.267004
12,شركت پارت چوب شاد ...,6203160240,19,0.849185
13,شركت افرا چوب ...,6100387332,9,0.835116
14,شركت احسان كار اصفهان ...,5113000739,8,0.699947
15,شركت تخته فشرده ممتاز گلستان ...,4838400303,12,0.662355
16,شركت چوب گستر كانيار ...,4781001600,22,0.654498
17,خوش چسب كرمان ...,4639974391,1,0.635192
18,شركت آرين مريم ...,4499053480,7,0.615900
19,شركت آرين سينا ...,3965751360,5,0.542894
20,يالماز اورمان(ياشار) ...,3707340215,24,0.507518
21,گروه صنعتي بازرگاني خادم/ ولي اله رضايي(آوا) ...,2941601770,25,0.402692
22,شركت تخته فشرده آريانا(پانيذ) ...,2575801445,10,0.352616
23,اتحاديه سراسري درودگران ...,1869692861,0,0.255953
24,شركت آرين شيمي ...,1739208779,6,0.238090
25,شركت صنايع چسب نوين گام ...,1360570700,16,0.186256

In [140]:
merge_data = merge_data.drop('Unnamed: 0' , axis=1)

# سه تامین کننده با بیشترین میزان فروش و سهم هر یک از کل خرید شرکت

In [141]:
merge_data

,Vendor_Name,Net Amount,Share_Total_Sales
0,شركت راش بينه ...,188564083823,25.813585
1,شركت پالار ...,173842152375,23.798218
2,شركت تخته فشرده شمال ...,103193429390,14.126722
3,شركت روكش آريا پويا ...,36595766438,5.009798
4,شركت نوين چوب فاليز ...,33460968105,4.580658
5,كيميا روكش گرگان ...,31649202645,4.332635
6,شركت خزر كاسپين ...,29407055875,4.025695
7,شركت ملامين سازه پويا ...,20473621510,2.802748
8,سندل چوب ...,17629202086,2.413359
9,شركت پويا چوب ...,16346298360,2.237736
10,زاگرس چوب سام ...,15731928319,2.153631
11,شركت آرين تخته ...,9255260369,1.267004
12,شركت پارت چوب شاد ...,6203160240,0.849185
13,شركت افرا چوب ...,6100387332,0.835116
14,شركت احسان كار اصفهان ...,5113000739,0.699947
15,شركت تخته فشرده ممتاز گلستان ...,4838400303,0.662355
16,شركت چوب گستر كانيار ...,4781001600,0.654498
17,خوش چسب كرمان ...,4639974391,0.635192
18,شركت آرين مريم ...,4499053480,0.615900
19,شركت آرين سينا ...,3965751360,0.542894
20,يالماز اورمان(ياشار) ...,3707340215,0.507518
21,گروه صنعتي بازرگاني خادم/ ولي اله رضايي(آوا) ...,2941601770,0.402692
22,شركت تخته فشرده آريانا(پانيذ) ...,2575801445,0.352616
23,اتحاديه سراسري درودگران ...,1869692861,0.255953
24,شركت آرين شيمي ...,1739208779,0.238090
25,شركت صنايع چسب نوين گام ...,1360570700,0.186256

# برترین تامین کننده ها در هر ماه از سال

In [142]:
purchase.head()

,date,ID,Vendor_code,Vendor_Name,Item_Code,Description,Unit,Quantity,Unit Price,Amount,Tax,Discount,Duties,Net Amount,Payment Date,Warehouse Serial
0,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-04-015,ملامينه 204*260 كد 1 سفيد درجه A ...,ورق ...,315.0,1879000,591885000,53269650,0,0,645154650,,536
1,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-04-022,ملامينه 204*260 كد 78 آنتيك لايت درجه A ...,ورق ...,45.0,2087000,93915000,8452350,0,0,102367350,,536
2,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-02-003,زيرپالتي نئوپان 204*260 ...,ورق ...,8.0,1,8,0,8,0,0,,536
3,13990117,1,1100251,شركت تخته فشرده شمال ...,1-1-02-009,زيرپالتي ام دي اف 3ميل ...,ورق ...,8.0,1,8,0,8,0,0,,536
4,13990119,2,1100249,شركت پالار ...,1-1-04-131,ملامينه 210*366 كد 1 سفيد درجه A ...,ورق ...,140.0,2674000,374360000,33692400,0,0,408052400,,537

In [143]:
purchase.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2221 entries, 0 to 2231
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              2221 non-null   int64
 1   ID                2221 non-null   int64
 2   Vendor_code       2221 non-null   int64
 3   Vendor_Name       2221 non-null   object
 4   Item_Code         2221 non-null   object
 5   Description       2221 non-null   object
 6   Unit              2221 non-null   object
 7   Quantity          2221 non-null   float64
 8   Unit Price        2221 non-null   int64
 9   Amount            2221 non-null   int64
 10  Tax               2221 non-null   int64
 11  Discount          2221 non-null   int64
 12  Duties            2221 non-null   int64
 13  Net Amount        2221 non-null   int64
 14  Payment Date      2221 non-null   object
 15  Warehouse Serial  2221 non-null   int64
dtypes: float64(1), int64(10), object(5)
memory usage: 295.0+ KB

In [144]:
wood = purchase.loc[: , ['Vendor_Name' , 'date' , 'Net Amount']].copy()

wood.head()

                                         Vendor_Name      date  Net Amount
0  شركت تخته فشرده شمال                          ...  13990117   645154650
1  شركت تخته فشرده شمال                          ...  13990117   102367350
2  شركت تخته فشرده شمال                          ...  13990117           0
3  شركت تخته فشرده شمال                          ...  13990117           0
4  شركت پالار                                    ...  13990119   408052400

In [145]:
wood.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2221 entries, 0 to 2231
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Vendor_Name  2221 non-null   object
 1   date         2221 non-null   int64
 2   Net Amount   2221 non-null   int64
dtypes: int64(2), object(1)
memory usage: 69.4+ KB

In [ ]:
import jdatetime as jdt
import jalali_pandas

In [157]:
def to_jalali_date(column, year_dir='L'): 
    if column.dtype == 'object':
        if '/' in column[0]:
            mod_col = [x.split('/') for x in column]
        elif '-' in column[0]:
            mod_col = [x.split('-') for x in column]
        elif '.' in column[0]:
            mod_col = [x.split('.') for x in column]
    
    elif column.dtype == 'int64':
        str_col = column.astype('str')
        if len(str(column[0])) == 8:
            if year_dir == 'L':
                mod_col = [[x[0:4], x[4:6], x[6:]] for x in str_col]
            elif year_dir == 'R':
                mod_col = [[x[0:2], x[2:4], x[4:]] for x in str_col]
        elif len(str(column[0])) == 6:
            mod_col = [[x[0:2], x[2:4], x[4:]] for x in str_col]

    if year_dir == 'L':
        year = [i[0] for i in mod_col]
        month = [i[1] for i in mod_col]
        day = [i[2] for i in mod_col]
    else:
        year = [i[2] for i in mod_col]
        month = [i[1] for i in mod_col]
        day = [i[0] for i in mod_col]

    if len(year[0]) == 2:
        if int(year[0]) < 50:
            year = ['14'+j for j in year]
        elif int(year[0]) > 50:
            year = ['13'+j for j in year]

    new_correct_date = []
    for n in range(len(year)):
        y = int(year[n])
        m = int(month[n])
        d = int(day[n])
        new_correct_date.append(jdt.date(y, m, d))  # jdt.datetime
    return new_correct_date

In [148]:
purchase.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2221 entries, 0 to 2231
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              2221 non-null   int64
 1   ID                2221 non-null   int64
 2   Vendor_code       2221 non-null   int64
 3   Vendor_Name       2221 non-null   object
 4   Item_Code         2221 non-null   object
 5   Description       2221 non-null   object
 6   Unit              2221 non-null   object
 7   Quantity          2221 non-null   float64
 8   Unit Price        2221 non-null   int64
 9   Amount            2221 non-null   int64
 10  Tax               2221 non-null   int64
 11  Discount          2221 non-null   int64
 12  Duties            2221 non-null   int64
 13  Net Amount        2221 non-null   int64
 14  Payment Date      2221 non-null   object
 15  Warehouse Serial  2221 non-null   int64
dtypes: float64(1), int64(10), object(5)
memory usage: 295.0+ KB

In [158]:
wood['Inv_Date'] = to_jalali_date(wood['date'])
wood.sample(5)

,Vendor_Name,date,Net Amount,Inv_Date,year,month,day
1785,شركت راش بينه ...,13990929,0,1399-09-29,1399,9,29
1596,كيميا روكش گرگان ...,13990901,0,1399-09-01,1399,9,1
1112,شركت پالار ...,13990702,0,1399-07-02,1399,7,2
2206,شركت پويا چوب ...,13991228,1117764480,1399-12-28,1399,12,28
76,شركت نوين چوب فاليز ...,13990207,0,1399-02-07,1399,2,7

In [150]:
wood.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2221 entries, 0 to 2231
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Vendor_Name  2221 non-null   object
 1   date         2221 non-null   int64
 2   Net Amount   2221 non-null   int64
 3   Inv_Date     2221 non-null   object
dtypes: int64(2), object(2)
memory usage: 151.3+ KB

In [159]:
wood['year']    = wood.Inv_Date.jalali.year
wood['month']   = wood.Inv_Date.jalali.month
wood['day'] = wood.Inv_Date.jalali.day

wood.sample(5)

,Vendor_Name,date,Net Amount,Inv_Date,year,month,day
1303,شركت ملامين سازه پويا ...,13990727,85142080,1399-07-27,1399,7,27
2186,شركت راش بينه ...,13991225,906990247,1399-12-25,1399,12,25
1720,كيميا روكش گرگان ...,13990923,2531200093,1399-09-23,1399,9,23
2122,شركت روكش آريا پويا ...,13991212,0,1399-12-12,1399,12,12
47,شركت پالار ...,13990202,0,1399-02-02,1399,2,2

In [152]:
best_vendor = wood.groupby(
                            ['Vendor_Name' , 'year' , 'month']
                        
                            )['Net Amount'].sum().reset_index()

best_vendor.head(12)

                                          Vendor_Name  year  month  Net Amount
0   اتحاديه سراسري درودگران                       ...  1399      5  1869692861
1   خوش چسب كرمان                                 ...  1399      2   423104864
2   خوش چسب كرمان                                 ...  1399      3   521033167
3   خوش چسب كرمان                                 ...  1399      6   572897634
4   خوش چسب كرمان                                 ...  1399      7   609066276
5   خوش چسب كرمان                                 ...  1399     10   809510518
6   خوش چسب كرمان                                 ...  1399     11   825736912
7   خوش چسب كرمان                                 ...  1399     12   878625020
8   زاگرس چوب سام                                 ...  1399      1  1056515200
9   زاگرس چوب سام                                 ...  1399      2  2235110400
10  زاگرس چوب سام                                 ...  1399      3  1252854720
11  زاگرس چوب سام                                 ...  1399      4  4848651360

In [153]:
wood.groupby(['Vendor_Name' , 'year' , 'month'] ) .ngroups

137

In [154]:
# .idxmx() _____ از برای پیدا کردن تأمین‌کننده‌ای که بالاترین فروش را در هر ماه دارد استفاده کنید.
top_vendor_month =best_vendor.loc[best_vendor.groupby( ['Vendor_Name' , 'year' , 'month'])['Net Amount'].idxmax()]
top_vendor_month

,Vendor_Name,year,month,Net Amount
0,اتحاديه سراسري درودگران ...,1399,5,1869692861
1,خوش چسب كرمان ...,1399,2,423104864
2,خوش چسب كرمان ...,1399,3,521033167
3,خوش چسب كرمان ...,1399,6,572897634
4,خوش چسب كرمان ...,1399,7,609066276
...,...,...,...,...
132,كيميا روكش گرگان ...,1399,11,2316000608
133,كيميا روكش گرگان ...,1399,12,4608000297
134,يالماز اورمان(ياشار) ...,1399,3,3707340215
135,گروه صنعتي بازرگاني خادم/ ولي اله رضايي(آوا) ...,1399,3,681600893
136,گروه صنعتي بازرگاني خادم/ ولي اله رضايي(آوا) ...,1399,4,2260000877

In [155]:
sort = top_vendor_month.sort_values( by= ['month' , 'Net Amount'] , ascending= [True , False])
sort.reset_index()

,index,Vendor_Name,year,month,Net Amount
0,66,شركت راش بينه ...,1399,1,15657923478
1,105,شركت پالار ...,1399,1,5450475240
2,8,زاگرس چوب سام ...,1399,1,1056515200
3,125,كيميا روكش گرگان ...,1399,1,995200346
4,41,شركت تخته فشرده شمال ...,1399,1,747522000
...,...,...,...,...,...
132,104,شركت پارت چوب شاد ...,1399,12,1872000078
133,65,شركت خزر كاسپين ...,1399,12,1811514600
134,36,شركت احسان كار اصفهان ...,1399,12,1417000000
135,40,شركت تخته فشرده آريانا(پانيذ) ...,1399,12,1035000780
136,7,خوش چسب كرمان ...,1399,12,878625020

In [156]:
top_vendor_1_month = top_vendor_month.groupby(['year', 'month']).first().reset_index()
top_vendor_1_month

    year  month                                        Vendor_Name  Net Amount
0   1399      1  زاگرس چوب سام                                 ...  1056515200
1   1399      2  خوش چسب كرمان                                 ...   423104864
2   1399      3  خوش چسب كرمان                                 ...   521033167
3   1399      4  زاگرس چوب سام                                 ...  4848651360
4   1399      5  اتحاديه سراسري درودگران                       ...  1869692861
5   1399      6  خوش چسب كرمان                                 ...   572897634
6   1399      7  خوش چسب كرمان                                 ...   609066276
7   1399      8  زاگرس چوب سام                                 ...  1583910671
8   1399      9  سندل چوب                                      ...  1600000013
9   1399     10  خوش چسب كرمان                                 ...   809510518
10  1399     11  خوش چسب كرمان                                 ...   825736912
11  1399     12  خوش چسب كرمان                                 ...   878625020